# Generated by Django 4.2.5 on 2023-10-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manageruser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user can access the admin site.",
            ),
        ),
    ]
