# Generated by Django 4.2.5 on 2023-09-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="temperature",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
