# Generated by Django 4.2.6 on 2023-10-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_timeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='clock_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
