# Generated by Django 4.2.5 on 2023-10-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_manageruser_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manageruser",
            name="is_staff",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user can access the admin site.",
            ),
        ),
    ]
