# Generated by Django 4.2.6 on 2023-10-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_timeentry_clock_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
